### ISSUE TITLE
What is localization contributions workflow?

### ISSUE THREAD

**Issue by skepsys** [StepicOrg/stepik-android#703]
Hi. We've [already translated](https://github.com/StepicOrg/stepik-i18n/pull/18) Stepik's website into Belarusian. And now want to contribute translations for the Android app.

I'm not an Android developer though, so it would be nice to clarify some moments before diving in. 

As far as I get, the workflow should be the following:

1. Create a fork
2. Translate strings in XML-files from `\app\src\main\res\values-ru\` 
3. Place translated files into `\app\src\main\res\values-be`. Any other configs should be made?
4. Create a pull request into master-branch (or any other?)

Please check if everything is right. Thanks.

**Comment by eadm** [comment]
Hi, thanks in advance!

1. ✅
2. ✅
3. ✅
4. Create a pull request into `development` branch

**Comment by skepsys** [comment]
Roger that. Thanks :)
